"""VYPER-5F pylon -- faired strut + motor nacelle. Two mirror hands, print 2 each.

PRINT ORIENTATION IS STILL THE WHOLE DESIGN
-------------------------------------------
Same argument as the plate version's arm, applied to a fairing. The pylon is
FLAT-TOPPED over its entire length -- strut and nacelle share one plane at the
motor mounting height -- and every bit of fairing hangs below it. So:

  * that flat top is the bed face AND the motor mounting face,
  * the plan section only ever shrinks going up from the bed, so there is not
    one overhang on the part, and
  * the bending fibres are continuous perimeters running root to tip.

This is why the pylons leave the fuselage at Z = +16 (the shoulder) rather
than at the waterline. A pylon that rose from the waterline to the motor pad
would put a 77-degree overhang along its whole upper surface, and you would be
printing the primary structure on supports.

The rounded belly comes from lofting one plan outline downward with a growing
inset (PYLON_BELLY). Strut and nacelle round off together, which is both the
look in the reference and a guarantee of monotonic shrink.

WHY IT IS BARELY STRESSED
-------------------------
A faired strut gets a deep section for free: 17 mm of depth against 19 N at
73.6 mm is about 1.4 N.m into a section modulus of ~750 mm^3, so roughly
1.8 MPa against ~45 MPa PETG yield. The nacelle fairing is doing structural
work as a side effect of doing aerodynamic work. Infill can stay low.

THE JOINT IS THE WEAK POINT, not the strut. The root flange is a saddle that
wraps the fuselage -- generated by subtracting the fuselage solid itself, so it
matches the mould line exactly -- with four M3 on an 18 mm couple arm running
into a backing rib inside the lower shell. Sized tall rather than wide because
the bending is vertical.

HANDS
-----
Front-left and rear-left are mirror images, not rotations, because the nacelle
is streamwise while the strut is swept. So there are two parts:
  hand A -> positions  45 deg and 225 deg (225 is A rotated 180 about Z)
  hand B -> positions 315 deg and 135 deg
"""

import math

from build123d import (
    Box,
    Cylinder,
    Plane,
    Polygon,
    Pos,
    RectangleRounded,
    Rot,
    loft,
    mirror,
    offset,
)

import body
import components as C
import vy_params as P

HANDS = {"a": 45.0, "b": 315.0}


def _root_offset(angle):
    """Root position relative to the motor, in frame axes."""
    rx, ry, _ = body.pylon_root(angle)
    mx, my, _ = body.motor_pos(angle)
    return (rx - mx, ry - my)


def _plan(angle):
    """Plan outline of strut + nacelle, in pylon-local XY (motor at origin)."""
    dx, dy = _root_offset(angle)
    span = math.hypot(dx, dy)
    ux, uy = dx / span, dy / span          # motor -> root
    vx, vy = -uy, ux                       # streamwise-ish perpendicular

    hcr = P.PYLON_CHORD_ROOT / 2
    hct = P.PYLON_CHORD_TIP / 2
    inner = 0.16                           # overlap into the nacelle

    pts = [
        (dx + hcr * vx, dy + hcr * vy),
        (inner * dx + hct * vx, inner * dy + hct * vy),
        (inner * dx - hct * vx, inner * dy - hct * vy),
        (dx - hcr * vx, dy - hcr * vy),
    ]
    strut = Polygon(*pts, align=None)
    nacelle = RectangleRounded(P.NACELLE_L, P.NACELLE_D, P.NACELLE_D / 2 - 0.01)
    return (strut + nacelle).clean()


def gen(hand="a"):
    """Hand A is built; hand B is hand A mirrored about its own XZ plane.

    Reconstructing hand B from mirrored inputs produces an inside-out loft --
    the plan outline's perpendicular flips sign, OCC builds a negatively
    oriented face, and every later boolean silently eats the part instead of
    cutting it. Mirroring the finished solid sidesteps that entirely and has
    the nicer property that the two hands are guaranteed to be exact mirrors.
    """
    if hand == "b":
        return mirror(gen("a"), about=Plane.XZ)
    angle = HANDS[hand]
    dx, dy = _root_offset(angle)
    span = math.hypot(dx, dy)
    ux, uy = dx / span, dy / span
    yaw = math.degrees(math.atan2(uy, ux))

    # ---- fairing: one plan outline lofted down with a growing inset
    plan = _plan(angle)
    sections = []
    for dz, ins in P.PYLON_BELLY:
        sk = offset(plan, -ins) if ins > 0 else plan
        sections.append(Plane.XY.offset(-dz) * sk)
    part = loft(sections)

    # ---- root flange. Straddles the root mostly OUTBOARD, because lower down
    # the fuselage bulges ~3 mm proud of the root plane and a flange centred on
    # the root would be eaten by the saddle cut.
    #
    # The four bolt holes are cut into the flange while it is still a clean
    # box. Cutting them after the saddle boolean puts a cylinder through a
    # freshly-trimmed spline surface, which segfaults the kernel.
    # ---- motor mount pocket, up into the nacelle belly.
    #
    # The nacelle is 17 mm deep. Bolting a motor through 17 mm of plastic would
    # need M3x22 and give no access. So the belly is hollowed out to leave a
    # 4.0 mm pad under the motor -- the same grip depth as the plate version,
    # so the same M3x8 motor screws work and the same warning applies: nothing
    # longer, or the screw goes into the windings.
    #
    # Printed pad-down this pocket opens upward. It is free to print, it takes
    # ~6 g out of each pylon, and it is where the motor wires land.
    pad_z = -P.MOTOR_PAD_T
    part -= Pos(0, 0, (pad_z - P.PYLON_DEPTH) / 2) * Cylinder(
        P.MOTOR_POCKET_D / 2, P.PYLON_DEPTH - P.MOTOR_PAD_T + 2
    )

    # ---- motor: 16 x 16 M3 + bell boss relief, through the 4 mm pad only
    h = C.MOTOR_PATTERN / 2
    for sx in (-h, h):
        for sy in (-h, h):
            part -= Pos(sx, sy, pad_z / 2) * Cylinder(
                P.M3_CLR / 2, P.MOTOR_PAD_T + 6
            )
    part -= Pos(0, 0, pad_z / 2) * Cylinder(4.5, P.MOTOR_PAD_T + 6)

    # ---- root flange. Straddles the root mostly OUTBOARD, because lower down
    # the fuselage bulges ~3 mm proud of the root plane and a flange centred on
    # the root would be eaten by the saddle cut.
    #
    # Every hole is cut while the flange is still a clean box, and the saddle
    # boolean is left until last. Cutting a cylinder through a freshly-trimmed
    # spline surface segfaults the kernel; this ordering is not cosmetic.
    cx = dx - (P.PYLON_FLANGE_T / 2 - P.PYLON_FLANGE_OUT) * ux
    cy = dy - (P.PYLON_FLANGE_T / 2 - P.PYLON_FLANGE_OUT) * uy
    flange = Box(P.PYLON_FLANGE_T, P.PYLON_FLANGE_W, P.PYLON_FLANGE_H)
    b = P.PYLON_FLANGE_BOLT
    for sv in (-b, b):
        for sz in (-b, b):
            flange -= Pos(0, sv, sz) * Rot(0, 90, 0) * Cylinder(
                P.M3_CLR / 2, P.PYLON_FLANGE_T + 10
            )
    part += Pos(cx, cy, -P.PYLON_FLANGE_H / 2) * Rot(0, 0, yaw) * flange

    # ---- wire tunnel: motor pocket -> through the strut -> out the flange,
    # cut after the union so it pierces both, but still before the saddle.
    # A 6 mm horizontal bore bridges cleanly at this size.
    part -= (
        Pos(0.5 * dx, 0.5 * dy, -P.WIRE_TUNNEL_Z)
        * Rot(0, 0, yaw)
        * Rot(0, 90, 0)
        * Cylinder(P.WIRE_CH_W / 2, span * 1.5)
    )

    # ---- saddle, LAST. Carve the fuselage itself out of the flange so the
    # mating face IS the mould line rather than an approximation of it.
    mx, my, _ = body.motor_pos(angle)
    part -= Pos(-mx, -my, -P.MOTOR_PAD_Z) * body.outer(P.SADDLE_GAP)

    return part.clean()


def gen_step():
    return gen("a")


if __name__ == "__main__":
    for h in HANDS:
        p = gen(h)
        bb = p.bounding_box()
        print(
            f"pylon_{h}: {p.volume:8.0f} mm^3  "
            f"{p.volume * P.PYLON_FILL * P.PETG_RHO:5.1f} g  "
            f"bbox {[round(v, 1) for v in bb.size]}"
        )
